---
name: Secret Scan

on:
  push:
  pull_request:

permissions: read-all

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0
          
      - name: Run TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@363923b901c911a9164f50b6c423f47c15372b1c # v3.97.4
        with:
          extra_args: --results=verified,unknown
